[package]
name = "rust-keyboard-spy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cocoa = "0.25.0"
rdev = "0.5.3"
rodio = "0.19.0"
